export enum InsertionMode {
  initialMode,
  afterInitialMode,
  // beforeHtmlMode,
  // beforeHeadMode,
  // inHeadMode,
  // inHeadNoScriptMode,
  // afterHeadMode,
  // inBodyMode,
  // textMode,
  // inTableMode,
  // inTableTextMode,
  // inCaptionMode,
  // inColumnGroupMode,
  // inTableBodyMode,
  // inRowMode,
  // inCellMode,
  // inSelectMode,
  // inSelectInTableMode,
  // inTemplateMode,
  // afterBodyMode,
  // inFramesetMode,
  // afterFramesetMode,
  // afterAfterBodyMode,
  // afterAfterFramesetMode,
}
